### PR TITLE
fix compiling tdesktop with -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION=ON

### LINKED ISSUE #65: ui_linux_wayland_integration_dummy.cpp lacks destructor
https://github.com/desktop-app/lib_ui/blob/3f85ce53d68bae6ca090e3389dec035f1fae0db7/ui/platform/linux/ui_linux_wayland_integration_dummy.cpp lacks destructor

So linking of `tdesktop` using `-DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION=ON` fails with
```
ui_linux_wayland_integration_dummy.cpp:(.text+0x4f): undefined reference to `Ui::Platform::WaylandIntegration::~WaylandIntegration()'
```

### PR DESCRIPTION
**Pull request by kvtb**
Fixes #65

### CODE REVIEW

**Comment by john-preston** [comment]
Thanks!

File: ui/platform/linux/ui_linux_wayland_integration_dummy.cpp [hunk 1]
```diff
@@ -17,6 +17,8 @@ struct WaylandIntegration::Private {
 
 WaylandIntegration::WaylandIntegration() {
 }
+	
+WaylandIntegration::~WaylandIntegration() = default;
```
Comment (mymedia2) [inline ui/platform/linux/ui_linux_wayland_integration_dummy.cpp:21]: You defined the destructor with C++11 `= default;` new syntax, however above, default constructor was already defined in old-fashioned way by empty braces `{}`. It remains a bit inconsistent. :disappointed:

Comment (kvtb) [reply ui/platform/linux/ui_linux_wayland_integration_dummy.cpp:21]: It is copy-paste from non-dummy implementation in
https://github.com/kvtb/lib_ui/blob/d8f436d9899cd6255180003ef948584f8a2cc63c/ui/platform/linux/ui_linux_wayland_integration.cpp#L72
